In [1]:
import cPickle as pickle
import numpy as np

In [5]:
X_train = pickle.load(open("/data1/stride6/data/doctorai_X_train.pkl"))
Y_train = pickle.load(open("/data1/stride6/data/doctorai_Y_train.pkl"))

X_val = pickle.load(open("/data1/stride6/data/doctorai_X_val.pkl"))
Y_val = pickle.load(open("/data1/stride6/data/doctorai_Y_val.pkl"))

X_test = pickle.load(open("/data1/stride6/data/doctorai_X_test.pkl"))
Y_test = pickle.load(open("/data1/stride6/data/doctorai_Y_test.pkl"))

print(len(X_train))
print(len(X_val))
print(len(X_test))

291421
97140
97141


In [10]:
# Okay, the inputs are pretty much the same; for outputs, we'll just use the presence/absence 
# of ccs codes at the end of each sequence. 
new_Y_train = []
for y_i in Y_train : 
    if y_i[-1][0] == 254 : 
        new_Y_train.append(1)
    else : 
        new_Y_train.append(0)
print(np.sum(np.array(new_Y_train)))

new_Y_val = []
for y_i in Y_val : 
    if y_i[-1][0] == 254 : 
        new_Y_val.append(1)
    else : 
        new_Y_val.append(0)
print(np.sum(np.array(new_Y_val)))

new_Y_test = []
for y_i in Y_test : 
    if y_i[-1][0] == 254 : 
        new_Y_test.append(1)
    else : 
        new_Y_test.append(0)
print(np.sum(np.array(new_Y_test)))

73761
24550
24591


In [11]:
pickle.dump(new_Y_train, open("/data1/stride6/data/retrain_Y_train.pkl", "wb"))
pickle.dump(new_Y_val, open("/data1/stride6/data/retrain_Y_val.pkl", "wb"))
pickle.dump(new_Y_test, open("/data1/stride6/data/retrain_Y_test.pkl", "wb"))


In [12]:
foo = np.zeros([10], dtype=np.float32)
for i, foo_i in enumerate(foo) : 
    foo_i = i
print(foo)

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [13]:
print(len(foo))

10


In [16]:
from util import * 
iterator = SequenceLabelIterator(X_train, new_Y_train, 3, 5, 15851)
x, y, seqlen, mask = iterator.next()

In [18]:
from __future__ import print_function
print("x: \n", x)
print("y: \n", y)
print("seqlen: \n", seqlen)
print("mask: \n", mask)

x: 
 [[[ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]]

 [[ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]
  [ 0.  0.  0. ...,  0.  0.  0.]]]
y: 
 [ 1.  0.  0.]
seqlen: 
 [1 5 5]
mask: 
 [[ 1.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [19]:
print(iterator.indices[:10])

[174818  44657  35158  90426 190072  35897   5144 107052  31947 205175]


In [20]:
print(new_Y_train[174818])

1


In [21]:
print(new_Y_train[44657])

0


In [22]:
print(new_Y_train[35158])

0


In [23]:
print(len(X_train[174818]))

1


In [24]:
print(len(X_train[44657]))

6


In [25]:
print(len(X_train[35158]))

53
